FROM webhippie/python:latest@sha256:27c8719b85ba459ce5b585b16b52b2b04db4f47cf8e7a2f252a0a2a073094cc0

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Pretalx" \
  org.label-schema.vcs-url="https://github.com/dockhippie/pretalx.git" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

EXPOSE 3000

WORKDIR /var/lib/pretalx
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/usr/bin/server"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/pretalx && \
  groupadd -g 1000 pretalx && \
  useradd -u 1000 -d /var/lib/pretalx -g pretalx -s /bin/bash -M pretalx && \
  apk add libxml2-dev libxslt-dev libressl-dev jpeg-dev mariadb-dev postgresql-dev sqlite-dev gettext && \
  pip3 install -U pretalx==0.7.1 setuptools wheel redis gunicorn django_redis dj_static psycopg2-binary mysqlclient && \
  rm -rf /var/cache/apk/*

COPY ./overlay ./overlay-amd64 /
