FROM webhippie/python:3.7-arm32v6@sha256:af67938fb808509251712f1d98c3d2769ced7d7ae20ab366022922c67456fa51

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Pretalx" \
  org.label-schema.version="0.7" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

EXPOSE 3000

WORKDIR /var/lib/pretalx
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/usr/bin/server"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/pretalx && \
  groupadd -g 1000 pretalx && \
  useradd -u 1000 -d /var/lib/pretalx -g pretalx -s /bin/bash -M pretalx && \
  apk add libxml2-dev libxslt-dev libressl-dev jpeg-dev mariadb-dev postgresql-dev sqlite-dev gettext && \
  pip3 install -U pretalx==0.7.1 setuptools wheel redis gunicorn django_redis dj_static psycopg2-binary mysqlclient && \
  rm -rf /var/cache/apk/*

COPY ./overlay ./overlay-arm32v6 /
