#!/bin/bash
source /usr/bin/entrypoint

if [[ ! -d ${PRETALX_DATA_DIR} ]]
then
  echo "> creating data directory"
  mkdir -p ${PRETALX_DATA_DIR}
fi

if [[ ! -d ${PRETALX_MEDIA_DIR} ]]
then
  echo "> creating media directory"
  mkdir -p ${PRETALX_MEDIA_DIR}
fi

if [[ ! -d ${PRETALX_LOGS_DIR} ]]
then
  echo "> creating logs directory"
  mkdir -p ${PRETALX_LOGS_DIR}
fi

if [[ ! -d ${PRETALX_STATIC_DIR} ]]
then
  echo "> creating static directory"
  mkdir -p ${PRETALX_STATIC_DIR}
fi

if [[ ${PRETALX_SKIP_CHOWN} == "true" ]]
then
  echo "> skipping data chown"
else
  echo "> fix data permission"
  find ${PRETALX_BASE_DIR} \( \! -user pretalx -o \! -group pretalx \) -print0 | xargs -r -0 chown pretalx:pretalx
fi

echo "> writing pretalx config"
/usr/bin/gomplate -V \
  -o /etc/pretalx/pretalx.cfg \
  -f /etc/templates/pretalx.tmpl

if [[ $? -ne 0 ]]
then
  echo "> writing config failed!"
  /bin/s6-svscanctl -t /etc/s6
  exit 1
fi

case "${PRETALX_DB_TYPE}" in
  "mysql")
    echo "> waiting for mysql"
    wait-for-it -t ${PRETALX_DB_TEST_TIMEOUT} ${PRETALX_DB_HOST}:${PRETALX_DB_PORT}

    if [[ $? -ne 0 && "${PRETALX_DB_TEST_FAIL}" == "true" ]]
    then
      echo "> database didn't come up in time!"
      /bin/s6-svscanctl -t /etc/s6
      exit 1
    fi
    ;;
  "pgsql")
    echo "> waiting for postgres"
    wait-for-it -t ${PRETALX_DB_TEST_TIMEOUT} ${PRETALX_DB_HOST}:${PRETALX_DB_PORT}

    if [[ $? -ne 0 && "${PRETALX_DB_TEST_FAIL}" == "true" ]]
    then
      echo "> database didn't come up in time!"
      /bin/s6-svscanctl -t /etc/s6
      exit 1
    fi
    ;;
esac

echo "> waiting for celery"
wait-for-it -t ${PRETALX_CELERY_TEST_TIMEOUT} ${PRETALX_CELERY_HOST}:${PRETALX_CELERY_PORT}

if [[ $? -ne 0 && "${PRETALX_CELERY_TEST_FAIL}" == "true" ]]
then
  echo "> celery didn't come up in time!"
  /bin/s6-svscanctl -t /etc/s6
  exit 1
fi

echo "> waiting for redis"
wait-for-it -t ${PRETALX_REDIS_TEST_TIMEOUT} ${PRETALX_REDIS_HOST}:${PRETALX_REDIS_PORT}

if [[ $? -ne 0 && "${PRETALX_REDIS_TEST_FAIL}" == "true" ]]
then
  echo "> redis didn't come up in time!"
  /bin/s6-svscanctl -t /etc/s6
  exit 1
fi
