#!/bin/bash
set -eo pipefail

declare -x PRETALX_CELERY_HOST
[[ -z "${PRETALX_CELERY_HOST}" ]] && PRETALX_CELERY_HOST="redis"

declare -x PRETALX_CELERY_PORT
[[ -z "${PRETALX_CELERY_PORT}" ]] && PRETALX_CELERY_PORT="6379"

declare -x PRETALX_CELERY_BACKENDDB
[[ -z "${PRETALX_CELERY_BACKENDDB}" ]] && PRETALX_CELERY_BACKENDDB="1"

declare -x PRETALX_CELERY_BROKERDB
[[ -z "${PRETALX_CELERY_BROKERDB}" ]] && PRETALX_CELERY_BROKERDB="2"

declare -x PRETALX_CELERY_TEST_TIMEOUT
[[ -z "${PRETALX_CELERY_TEST_TIMEOUT}" ]] && PRETALX_CELERY_TEST_TIMEOUT="60"

declare -x PRETALX_CELERY_TEST_FAIL
[[ -z "${PRETALX_CELERY_TEST_FAIL}" ]] && PRETALX_CELERY_TEST_FAIL="true"

true
