FROM webhippie/python:3.12-amd64@sha256:c37ca5ff629b0a39ae592d0cdc5c4ce92761ff86a48b838df2413147a774beda

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Pretalx" \
  org.label-schema.version="1.1" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

EXPOSE 3000

WORKDIR /var/lib/pretalx
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/usr/bin/server"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/pretalx && \
  groupadd -g 1000 pretalx && \
  useradd -u 1000 -d /var/lib/pretalx -g pretalx -s /bin/bash -M pretalx && \
  apk add libxml2-dev libxslt-dev libressl-dev jpeg-dev mariadb-dev postgresql-dev sqlite-dev gettext && \
  pip3 install -U pretalx==1.1.2 setuptools wheel typing redis gunicorn django_redis psycopg2-binary mysqlclient && \
  rm -rf /var/cache/apk/*

COPY ./overlay ./overlay-amd64 /
