#!/bin/bash

declare -x PRETALX_REDIS_HOST
[[ -z "${PRETALX_REDIS_HOST}" ]] && PRETALX_REDIS_HOST="redis"

declare -x PRETALX_REDIS_PORT
[[ -z "${PRETALX_REDIS_PORT}" ]] && PRETALX_REDIS_PORT="6379"

declare -x PRETALX_REDIS_DB
[[ -z "${PRETALX_REDIS_DB}" ]] && PRETALX_REDIS_DB="0"

declare -x PRETALX_REDIS_SESSION
[[ -z "${PRETALX_REDIS_SESSION}" ]] && PRETALX_REDIS_SESSION="False"

declare -x PRETALX_REDIS_TEST_TIMEOUT
[[ -z "${PRETALX_REDIS_TEST_TIMEOUT}" ]] && PRETALX_REDIS_TEST_TIMEOUT="60"

declare -x PRETALX_REDIS_TEST_FAIL
[[ -z "${PRETALX_REDIS_TEST_FAIL}" ]] && PRETALX_REDIS_TEST_FAIL="true"

declare -x PRETALX_REDIS="redis://${PRETALX_REDIS_HOST}/${PRETALX_REDIS_DB}"
